#!/bin/bash

# FlowPilot Screenshot Extraction Helper
# This script helps extract image URLs from share.md for manual download

echo "==================================="
echo "FlowPilot Screenshot URLs"
echo "==================================="
echo ""
echo "Since these images are hosted on an internal corporate network,"
echo "please open each URL in your browser and save them manually."
echo ""
echo "-----------------------------------"
echo "Image 1: banner.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:3167188162034564394fcABjnTyDXj_V_VNLfgLHM-YD:1763384369107"
echo "Save to: public/screenshots/banner.png"
echo ""

echo "-----------------------------------"
echo "Image 2: feature-chat-cat.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-3005920242718049600fcABjnTyDXj_V_VNLfgLHM-YD:1763384369108"
echo "Save to: public/screenshots/feature-chat-cat.png"
echo ""

echo "-----------------------------------"
echo "Image 3: feature-chat-dog.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:3228178480041103531fcABjnTyDXj_V_VNLfgLHM-YD:1763384369108"
echo "Save to: public/screenshots/feature-chat-dog.png"
echo ""

echo "-----------------------------------"
echo "Image 4: feature-style-original.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:2088457989885341663fcABjnTyDXj_V_VNLfgLHM-YD:1763384369108"
echo "Save to: public/screenshots/feature-style-original.png"
echo ""

echo "-----------------------------------"
echo "Image 5: feature-style-generated.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-3429045031859737651fcABjnTyDXj_V_VNLfgLHM-YD:1763384369108"
echo "Save to: public/screenshots/feature-style-generated.png"
echo ""

echo "-----------------------------------"
echo "Image 6: feature-brief-config.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:5076325540898615997fcABjnTyDXj_V_VNLfgLHM-YD:1763384369108"
echo "Save to: public/screenshots/feature-brief-config.png"
echo ""

echo "-----------------------------------"
echo "Image 7: feature-sequence-formal.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-6544881212478781000fcABjnTyDXj_V_VNLfgLHM-YD:1763384369108"
echo "Save to: public/screenshots/feature-sequence-formal.png"
echo ""

echo "-----------------------------------"
echo "Image 8: feature-sequence-sketch.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:1836148692676380082fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/feature-sequence-sketch.png"
echo ""

echo "-----------------------------------"
echo "Image 9: feature-model-selection.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-1862551751719320689fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/feature-model-selection.png"
echo ""

echo "-----------------------------------"
echo "Image 10: feature-model-comparison.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-3112982623129742660fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/feature-model-comparison.png"
echo ""

echo "-----------------------------------"
echo "Image 11: feature-model-config.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-8733473680767249177fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/feature-model-config.png"
echo ""

echo "-----------------------------------"
echo "Image 12: feature-ppt-input.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:7228850631256574744fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/feature-ppt-input.png"
echo ""

echo "-----------------------------------"
echo "Image 13: feature-ppt-output.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:1692396851258385169fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/feature-ppt-output.png"
echo ""

echo "-----------------------------------"
echo "Image 14: example-diagram-1.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:1888198707985133685fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/example-diagram-1.png"
echo ""

echo "-----------------------------------"
echo "Image 15: example-diagram-2.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:3796899254975046411fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/example-diagram-2.png"
echo ""

echo "-----------------------------------"
echo "Image 16: example-diagram-3.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:1437829768119417425fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/example-diagram-3.png"
echo ""

echo "-----------------------------------"
echo "Image 17: example-diagram-4.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:4769143755415665585fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/example-diagram-4.png"
echo ""

echo "-----------------------------------"
echo "Image 18: example-diagram-5.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-7728609183008724058fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/example-diagram-5.png"
echo ""

echo "-----------------------------------"
echo "Image 19: example-diagram-6.png"
echo "URL: https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcABjnTyDXj_V_VNLfgLHM-YD:-4075463795420338805fcABjnTyDXj_V_VNLfgLHM-YD:1763384369109"
echo "Save to: public/screenshots/example-diagram-6.png"
echo ""

echo "==================================="
echo "Total: 19 images to download"
echo "==================================="
echo ""
echo "Instructions:"
echo "1. Open each URL in your browser"
echo "2. Right-click and save the image"
echo "3. Save to the specified path in public/screenshots/"
echo ""
